spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
      - id: Product-service
        uri: http://localhost:9001/
        predicates:
          - Path=/home/**
      - id: UserAdmin-service
        uri: http://localhost:9004/
        predicates:
          - Path=/**
